version: '3'

services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - ./stutzdb:/data/db
    ports:
      - 27020:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']
  
  escr-app:
    depends_on:
      - db
    # image: javierpazz/jpzstutz
    image: stutz
    ports:
      - 4000:3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MONGODB_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB_NAME}:27017

    restart: always

# volumes:
#   stutzdb:
#     external: true